package com.qwerky.offermanagement.rules;

import com.qwerky.offermanagement.model.Offer;

rule "Select Banner Offer if it exists"
when
    $bannerOffer : Offer(seller.name == "BQUK")
    $nonBannerOffer : Offer(seller.name != "BQUK")
then
    $bannerOffer.setValid(true);
    update($bannerOffer);
    $nonBannerOffer.setValid(false);
    update($nonBannerOffer);
end


rule "Select Lowest Price Offer if no banner offers"
when
    not Offer(seller.name == "BQUK")
    $lowestPriceOffer : Offer($price : pricing.currentPrice)
    not(Offer(pricing.currentPrice < $price, seller.name != "BQUK"))
    $nonLowestOffers : Offer(pricing.currentPrice > $price)
then
    $lowestPriceOffer.setValid(true);
    update($lowestPriceOffer);
    $nonLowestOffers.setValid(false);
    update($nonLowestOffers)
end
